import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "dist-desktop/**",
    "out/**",
    "resources/**",
    "build/**",
    // Generated by scripts/build-desktop-plugins.mjs and includes bundled xterm sources.
    "packages/laobos-ssh/lib/client.js",
    "packages/laobos-terminal-ui/lib/client.js",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
